In [1]:
################################################################################                                                                                                                                                              
################################################################################
#
# FILE: commercialexchange-retail-rent-download-test.ipynb
#
# BY: Dmitry Sedov 
#
# CREATED: Mon Mar 30 2020
#
# DESC: This code [tests] rent data download from commercialexchange.com.
#
# EXEC:
#      
################################################################################
################################################################################

In [2]:
############################### Libraries ######################################

import requests
from bs4 import BeautifulSoup
import pandas as pd
import os
import us
import json

################################################################################

In [26]:
######################### Constants and settings ###############################

url_search = 'https://api.commercialexchange.com/api/cfra/ee/search/properties/_list?pageSize=100&sort=QUALITY%3Adesc&byProperty=true'
url_property = 'https://api.commercialexchange.com/api/cfra/ee/property/{}'

user_agent = 'Moilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36'

output_folder_path = '/home/user/projects/urban/data/input/Rent/commercialexchange/retail'

form_data = {'pageNumber':1,
             'locations':[{'postalCode':'54016'}],
             'listedStatus':['AVAILABLE_LEASE']
            }

headers_search = {'x-api-key': '***REMOVED***',
                  'user-agent': user_agent,
                  'content-type': 'application/json',
                  'accept': 'application/json'
                 }

headers_property = {'x-api-key': '***REMOVED***',
                    'user-agent': user_agent,
                    'accept': 'application/json'
                   }

################################################################################

In [27]:
session = requests.Session()

In [28]:
result = session.post(url_search, data = json.dumps(form_data), headers = headers_search)

In [29]:
result.json()

{'total': 34,
 'pageNumber': 1,
 'pageSize': 100,
 'results': [{'data': {'name': '1301 Gateway Cir',
    'subCategory': 'WAREHOUSE_OFFICE',
    'id': '5dc46fc36348830001275fe6',
    'category': 'INDUSTRIAL',
    '_score': 0,
    'listedSpaces.ids': ['5e73f32a8e5d41000162799b',
     '5e7b65b660abf50001ca8e5d']}},
  {'data': {'name': '2351 Coulee Rd',
    'subCategory': 'BIG_BOX',
    'id': '5e569e0a14e1490001a6399c',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5e56a0aa7a35a9000169d715']}},
  {'data': {'name': 'Hudson Marketplace West',
    'subCategory': 'STRIP_CENTER',
    'id': '5a9421e5a0b9c600014d2494',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5e542cc94a0a580001187bed',
     '5b4d0898b389aa000155ad08']}},
  {'data': {'name': 'Ban Tara Retail Center',
    'subCategory': 'STRIP_CENTER',
    'id': '5cb5cf02782580000145dc35',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5cb5de29782580000145e849',
     '5e4c3ae07aee99000127bb30']}},
  {'data': {'name': '1021-1027 Pearson Dr',
    'subCategory': 'STRIP_CENTER',
    'id': '5e4c36190714bf000146789d',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5e4c38ad7aee990001278fad']}},
  {'data': {'name': 'Monetary Center',
    'category': 'OFFICE',
    'id': '5adfa1afd12ba30001134514',
    '_score': 0,
    'listedSpaces.ids': ['5e4c3440e9bb470001d5d94c',
     '5e4c3574ad12d40001694d96']}},
  {'data': {'name': '749 Ryan Dr',
    'subCategory': 'MIXED_USE',
    'id': '5e4452d15ee36f00016118bc',
    'category': 'OFFICE',
    '_score': 0,
    'listedSpaces.ids': ['5e44637157362d0001ccd70e']}},
  {'data': {'name': 'Hudson Business Center',
    'subCategory': 'MANUFACTURING',
    'id': '5adf9cb6d12ba30001132f5e',
    'category': 'INDUSTRIAL',
    '_score': 0,
    'listedSpaces.ids': ['5e138d1ff4010f00015a4e38']}},
  {'data': {'name': '206 2nd St',
    'subCategory': 'MIXED_USE',
    'id': '5aba5a28667517000147dd05',
    'category': 'OFFICE',
    '_score': 0,
    'listedSpaces.ids': ['5e39b8d372e81e0001dba092',
     '5df9200e26d51b0001737aaa']}},
  {'data': {'name': 'Carmichael Professional Building',
    'subCategory': 'MEDICAL_DENTAL',
    'id': '5b631e1a7bdd500001bc6d2b',
    'category': 'OFFICE',
    '_score': 0,
    'listedSpaces.ids': ['5e25e9173260b50001e9c4bc',
     '5e25e9173260b50001e9c4bf']}},
  {'data': {'name': 'Hudson Business Park - Condo 105',
    'category': 'OFFICE',
    'id': '5adfa118d12ba30001134280',
    '_score': 0,
    'listedSpaces.ids': ['5e0e326664bb1000018a703d']}},
  {'data': {'name': 'Towerview Business Center',
    'subCategory': 'WAREHOUSE_FLEX',
    'id': '5adf9c3ed12ba30001132b78',
    'category': 'INDUSTRIAL',
    '_score': 0,
    'listedSpaces.ids': ['5bd9f40f25a0bd000198ff56',
     '5d14dea35dfdb80001181d63',
     '5d14decdf6aa0900017cca3f',
     '5e0624caca61a80001b25b21']}},
  {'data': {'name': 'River City Center',
    'subCategory': 'STRIP_CENTER',
    'id': '5d4af5b4a2498a0001082e81',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5d4af933a2498a0001083363',
     '5d4af99e0187730001bd5d8b',
     '5d4afa05a2498a0001083499',
     '5d4afa480187730001bd5e4f']}},
  {'data': {'name': '401 2nd St',
    'subCategory': 'MIXED_USE',
    'id': '5bbcdc3dd2d9ec00011f3b3a',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5cad044af9109500013e9ca0',
     '5cad0617f9109500013ea1d4']}},
  {'data': {'name': '709 Rodeo Dr',
    'subCategory': 'STRIP_CENTER',
    'id': '5c89883cdd0e1d000190214f',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5c898a29dd0e1d00019022ee',
     '5c898affdd0e1d00019023ce',
     '5c898affdd0e1d00019023d2']}},
  {'data': {'name': '707 Rodeo Dr ',
    'subCategory': 'STRIP_CENTER',
    'id': '5c892dd2b7b78f0001b251d0',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5c89333a11e6d90001ca61f7']}},
  {'data': {'name': '706 19th St',
    'subCategory': 'STRIP_CENTER',
    'id': '5b9bf323717fc40001637105',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5b9bf6150bae4e0001e172a7']}},
  {'data': {'name': '650 Brakke Dr',
    'subCategory': 'WAREHOUSE_OFFICE',
    'id': '5b8ec42797aab0000142bdd7',
    'category': 'INDUSTRIAL',
    '_score': 0,
    'listedSpaces.ids': ['5b8ec675712c0c0001182cd3']}},
  {'data': {'name': 'Plaza 94 Shopping Center',
    'category': 'RETAIL',
    'id': '5a96ccc4c0b2c80001bb2ee0',
    '_score': 0,
    'listedSpaces.ids': ['5a96d069bccff00001708150',
     '5ae222e78f244a00014e9ba2']}},
  {'data': {'name': '606 Brakke Dr',
    'subCategory': 'STRIP_CENTER',
    'id': '5ae1e6d8b9e60b000165af59',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5ae1f2e1c2385c000108ffd9']}},
  {'data': {'name': '529 2nd St ',
    'subCategory': 'STRIP_CENTER',
    'id': '5adfa223d12ba300011347e4',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5e4d9d66c3fec600011c76e1']}},
  {'data': {'name': '642 Brakke Dr',
    'category': 'OFFICE',
    'id': '5df930c2f71e4400011bc291',
    '_score': 0,
    'listedSpaces.ids': ['5df932fa94bdcc0001bbe56b']}},
  {'data': {'name': 'Fiesta Cancun',
    'subCategory': 'RESTAURANT',
    'id': '5ad7c6dc1e6b6500010cd931',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5deff27d5fe3a900019539e7']}},
  {'data': {'name': 'Charmichael Rd, S of Vine St',
    'subCategory': 'STRIP_CENTER',
    'id': '5dd6e03412ff440001cca7fb',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5dd6e4a3faea4800016f5090']}},
  {'data': {'name': 'Hudson Center',
    'subCategory': 'STRIP_CENTER',
    'id': '5cb60e4d0ca45600016fc033',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5cb60fa30ca45600016fc218']}},
  {'data': {'name': '2201 Badger Dr',
    'category': 'LAND',
    'id': '5cb60ccd7825800001462072',
    '_score': 0,
    'listedSpaces.ids': ['5cb60e2778258000014622bb']}},
  {'data': {'name': 'Ban Tara Retail Center',
    'subCategory': 'STRIP_CENTER',
    'id': '5cb6080678258000014619ac',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5cb60a3d7825800001461c92']}},
  {'data': {'name': '2501 Hanley Rd',
    'category': 'OFFICE',
    'id': '5cb5edb3782580000145f8cb',
    '_score': 0,
    'listedSpaces.ids': ['5cb5f2890ca45600016f993d',
     '5cb5f29b0ca45600016f9968']}},
  {'data': {'name': '625 Commerce Drive',
    'subCategory': 'MEDICAL_DENTAL',
    'id': '5ad76c2e1e6b6500010cd7fd',
    'category': 'OFFICE',
    '_score': 0,
    'listedSpaces.ids': ['5ad7a389e2d4710001cd400a']}},
  {'data': {'name': 'Ban Tara Lot 3',
    'subCategory': 'COMMUNITY_SPECIALTY',
    'id': '5ad77afe1e6b6500010cd83b',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5cb5fd420ca45600016fa7a9',
     '5ad77bbae2d4710001cd3f7c']}},
  {'data': {'name': 'Ban Tara Retail Center',
    'subCategory': 'COMMUNITY_SPECIALTY',
    'id': '5ad77a15e2d4710001cd3f76',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5cb5da65782580000145e511',
     '5cb5da650ca45600016f8124',
     '5ad77adfe2d4710001cd3f79']}},
  {'data': {'name': '2521 Hanley Rd',
    'subCategory': 'COMMUNITY_SPECIALTY',
    'id': '5ad778921e6b6500010cd833',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5ad779bde2d4710001cd3f73']}},
  {'data': {'name': 'Hudson Tourist Center',
    'subCategory': 'STRIP_CENTER',
    'id': '5ad7767de2d4710001cd3f68',
    'category': 'RETAIL',
    '_score': 0,
    'listedSpaces.ids': ['5ad77845e2d4710001cd3f6e']}},
  {'data': {'name': 'Hudson Hospital Specialty Clinic',
    'subCategory': 'MEDICAL_DENTAL',
    'id': '5a956b0ab9ec950001cb9f09',
    'category': 'OFFICE',
    '_score': 0,
    'listedSpaces.ids': ['5a956c3044e13c00013d7eb5']}}]}

In [7]:
properties = [x['data']['id'] for x in result.json()['results']]

In [8]:
result_search = session.get(url_property.format(properties[3]), headers = headers_property)

In [9]:
result_search.json()

{'parcels': [{'APN': '41-14-32-127-011', 'FIPS': '26081'}],
 'name': '1144 Wealthy St SE',
 'category': 'RETAIL',
 'subCategory': 'MIXED_USE',
 'location': {'address': {'street': {'name': 'Wealthy St SE',
    'numberMin': 1144},
   'country': 'USA',
   'postalCode': '49506',
   'locality': 'Grand Rapids',
   'region': 'MI'},
  'county': 'Kent',
  'submarket': 'East Grand Rapids',
  'nearestMSA': 'Grand Rapids-Kentwood',
  'geopoint': {'latitude': 42.9553579, 'longitude': -85.640174}},
 'buildings': {'buildingStatus': 'EXISTING',
  'construction': {'yearBuilt': 1926, 'yearRenovated': 2006},
  'condominiumized': False,
  'physicalCharacteristics': {'clearHeightMinFt': 9.0,
   'clearHeightMaxFt': 14.0,
   'railService': False},
  'size': {'grossSF': 3120, 'rentableSF': 3120},
  'certifications': [{'type': 'LEED', 'value': '0'}]},
 'lot': {'zoning': 'N/A', 'totalAcres': 0.15},
 'utilities': {'electric': {'available': False},
  'water': {'available': True},
  'sanitarySewer': {'available': True}},
 'occupancy': {'type': 'MULTI_TENANT'},
 'createdDate': {'$date': '2019-11-04T14:23:04Z'},
 'modifiedDate': {'$date': '2020-02-26T18:56:10.178Z'},
 'media': [{'url': '/cie-media/00/22/82/40/98/RAW.JPG', 'type': 'IMAGE'}],
 'source': {'name': 'CIE', 'id': '6725590'},
 'id': '5cc0a159b5ab220001dfa8a3',
 'listedSpaces': [{'title': '1144 Wealthy St. SE',
   'availability': {'status': 'AVAILABLE',
    'availableDate': {'$date': '2020-01-01T00:00:00Z'}},
   'type': 'LEASE',
   'commision': {'description': '3/3/0'},
   'space': {'suite': '1',
    'condo': False,
    'category': 'RETAIL',
    'physicalCharacteristics': {'clearHeightMinFt': 9.0,
     'clearHeightMaxFt': 14.0,
     'doors': {'dockHighDoors': {'present': False},
      'gradeLevelDoors': {'present': False}}},
    'size': {'available': 1560.0,
     'minimumDivisible': 1560.0,
     'maximumContiguous': 1560.0,
     'units': 'SQUARE_FEET'}},
   'lease': {'askingRent': [{'type': 'GENERAL',
      'price': {'amount': {'minimum': {'currency': 'USD', 'amount': 15.5},
        'maximum': {'currency': 'USD', 'amount': 15.5}},
       'period': 'ANNUAL',
       'size': 'SF'}}],
    'leaseType': 'NNN',
    'sublease': False},
   'agents': [{'name': 'Jeffrey A Tucker',
     'contactMethods': [{'method': 'PHONE',
       'value': '616-881-9321',
       'primary': True}],
     'organizations': [{'id': 'CARWM'}],
     'company': {'website': 'http://www.bradleyco.com',
      'postalAddress': {'country': 'USA',
       'streetAddress': '161 Ottawa Ave. NW Suite 308',
       'postalCode': '49503',
       'locality': 'Grand Rapids',
       'region': 'MI'},
      'name': 'Bradley Company',
      'contactMethods': [{'method': 'PHONE',
        'value': '616-254-0005',
        'primary': True}],
      'logo': {'url': '/cie-media/00/07/15/23/20/RAW.JPG'},
      'id': '5d1a1ca5850c2c000155d90e'},
     'officeRole': 'BROKER_AGENT',
     'biography': ' Jeff Tucker is a seasoned sales and marketing professional with over 24 years of real estate experience. He joined Bradley Company as Vice President, Office Brokerage in September 2016.  In his role, Mr. Tucker assists clients in strategic planning, transaction execution for both acquisition and dispositions, and portfolio management throughout the Michigan region.  He enjoys client relationships with Fortune 500 companies as well as family owned businesses.\r\nMr. Tucker attended Hope College where he graduated with a degree in Political Science.  He is dedicated to providing unsurpassed customer service, coupled with uncompromising integrity and the highest industry standards.\r\n',
     'picture': {'url': '/cie-media/00/10/48/77/68/RAW.JPG'},
     'id': '5d2945ae363cef0001ca51b2',
     'role': 'LISTING_AGENT'}],
   'remarksForPublic': 'Come uptown to the Wealthy Street corridor.  Newly renovated street retail/office suite with LEED efficiency.  Great for salon, retail, restaurant, or studio/office space. ',
   'createdDate': {'$date': '2019-11-04T14:23:05Z'},
   'modifiedDate': {'$date': '2019-12-06T13:58:07.041Z'},
   'startDate': {'$date': '2019-11-01T00:00:00Z'},
   'media': [{'type': 'IMAGE',
     'url': '/cie-media/00/22/82/40/98/RAW.JPG',
     'name': 'Main Photo',
     'order': 0,
     'createdDate': {'$date': '2019-11-04T14:23:05Z'}}],
   'source': {'name': 'CIE',
    'id': '30525603_4673793',
    'displayableName': 'CARWM',
    'logo': 'https://mls.carwm.com/images/logo/cie-small/logo_40476206.gif',
    'url': 'https://mls.carwm.com'},
   'restrictedTo': ['o-5bd24d1f841251eeccf88796'],
   'excludeFromAnalytics': True,
   'property': {'id': '5cc0a159b5ab220001dfa8a3'},
   'publicId': '23883699',
   'id': '5dc08936459fb400018c2702'}]}

In [14]:
output_folder_path_search = '/home/user/projects/urban/data/input/Rent/commercialexchange/retail/search'
search_results = pd.read_csv(os.path.join(output_folder_path_search, 'commercialexchange-search.csv'))

In [15]:
search_results.head()

   zip_code  total_results  page_number  page_size property_ids
0       501              0            1         50           []
1       544              0            1         50           []
2       601              0            1         50           []
3       602              0            1         50           []
4       603              0            1         50           []

In [25]:
search_results['total_results'].value_counts()

0     38879
1      1426
2       686
3       403
4       267
5       195
6       164
7       127
8        93
9        80
10       48
11       45
12       36
13       31
14       28
15       20
18       13
19       12
16       11
17       11
20       10
22        6
24        6
29        4
21        4
25        4
28        3
23        3
32        2
26        2
27        2
31        2
36        2
30        2
38        1
34        1
50        1
44        1
39        1
Name: total_results, dtype: int64

In [89]:
property_ids = search_results['property_ids'].tolist()

In [90]:
property_ids = [eval(x) for x in property_ids]

In [91]:
property_ids = [item for sublist in property_ids for item in sublist]

In [93]:
len(property_ids)

14212

In [45]:
output_folder_path_search = '/home/user/projects/urban/data/input/Rent/commercialexchange/all/search'
search_results = pd.read_csv(os.path.join(output_folder_path_search, 'commercialexchange-all-search.csv'))

In [50]:
pd.DataFrame(search_results['total_results'].value_counts())

     total_results
0            37102
1             1730
2              708
3              433
4              327
5              226
6              178
7              167
8              136
9              123
10             122
11             116
12              88
13              74
14              74
15              69
18              62
16              55
17              55
21              51
22              45
20              45
23              43
19              36
24              36
26              36
25              34
28              29
29              28
34              22
27              22
30              22
37              19
31              19
47              17
40              17
35              16
33              16
32              14
36              14
43              13
45              13
39              13
41              10
44              10
57               9
42               8
38               8
51               7
50               6
58               6
68               5
64               5
46               5
56               5
70               4
52               4
78               4
54               4
48               4
65               3
90               3
55               3
77               3
49               3
74               3
53               2
91               2
82               2
93               2
72               2
79               2
87               2
71               2
84               2
69               2
59               2
107              1
98               1
73               1
63               1
92               1
67               1
124              1
96               1
94               1
121              1
111              1
120              1
88               1
81               1
133              1
86               1
76               1
102              1
103              1
83               1
104              1
168              1
127              1

In [41]:
property_ids = search_results['property_ids'].tolist()
property_ids = [eval(x) for x in property_ids]

In [42]:
property_ids = [item for sublist in property_ids for item in sublist]

In [43]:
len(property_ids)

14212

In [49]:
pd.options.display.max_rows = 100